// Text measurement, and the line breaks it predicts.
//
// This is what lets the content gate catch overlong copy before a deck is
// built, rather than after a render round shows it overflowing. Overflow is
// repaired by shortening text, so knowing it early is worth a whole round.
//
// The numbers come from font-advances.js, generated by
// scripts/derive-font-metrics.js from the real font files. They are Arial's,
// which is the metric the reference deck's Latin actually sets in - the
// typeface design.js declares carries no Latin glyphs at all, so nothing in it
// can be measured for English copy. The deriving script records the evidence.
//
// Two ways this prediction is deliberately conservative, both of which make it
// report slightly *more* width than a renderer will use:
//
//   - it sums advance widths and ignores pair kerning, which only ever pulls
//     glyphs closer together;
//   - an advance includes the last glyph's right side bearing, while the ink a
//     reader sees stops short of it.
//
// Erring wide is the right direction for a gate. A prediction that ran narrow
// would pass copy that then overflowed in PowerPoint, which is the failure this
// exists to prevent.

const { ADVANCES, NOTDEF } = require('./font-advances.js');

/**
 * How wide a string sets, in inches.
 *
 * @param {string} text
 * @param {{fontSize: number, bold?: boolean}} options  Type size in points.
 * @returns {number}
 */
function textWidth(text, { fontSize, bold = false }) {
  const weight = bold ? 'bold' : 'regular';
  const advances = ADVANCES[weight];
  const fallback = NOTDEF[weight];

  let em = 0;
  // Iterated by code point rather than by index, so a character outside the
  // table costs one fallback advance instead of two.
  for (const character of String(text)) em += advances[character] ?? fallback;

  return (em * fontSize) / 72;
}

/**
 * How many lines a string takes in a column of a given width.
 *
 * Words are kept whole, which is what a renderer does: a word too wide for the
 * column takes its own line and overhangs it rather than being split. That case
 * still counts as one line here, and it is the fit check's business to notice
 * that the line is wider than the box.
 *
 * @param {string} text
 * @param {{width: number, fontSize: number, bold?: boolean}} options  Width in inches.
 * @returns {number}
 */
function wrapLines(text, { width, fontSize, bold = false }) {
  const words = String(text).split(/\s+/).filter(Boolean);
  // An empty field still occupies its line, and reporting 0 would make an empty
  // box look like it had room to spare.
  if (words.length === 0) return 1;

  const space = textWidth(' ', { fontSize, bold });
  let lines = 1;
  let used = 0;

  for (const word of words) {
    const wide = textWidth(word, { fontSize, bold });
    // The first word on a line is always placed, however wide it is: moving it
    // to the next line would leave this one empty and never terminate.
    if (used === 0) {
      used = wide;
      continue;
    }

    if (used + space + wide <= width) {
      used += space + wide;
    } else {
      lines += 1;
      used = wide;
    }
  }

  return lines;
}

module.exports = { textWidth, wrapLines };
